### PR TITLE
Fix Only one detection per print

### LINKED ISSUE #9: Only one detection per print
Here is my problem:
I print and filament jams/ends: plugin works fine. M600 is send correctly.
I continue print and filament jams/ends second time during the same print: plugin DOESN'T work. M600 is NOT send. I checked using that special testing script, that motion is NOT detected, but M600 is not send. When I send M600 manually, it works, so it's not printer problem. 
Do You have any idea if this is bug or configuration problem? If You want my help contact me at: pioole282@gmail.com. I'm Python programmer and I have a bit of free time, so I thing that I might be able to help :)

### PR DESCRIPTION
**Pull request by Pavulon87**
Reset send_code with every movement
Fix #9

### CODE REVIEW

**Comment by Haku73** [comment]
Hi,

it gives me this error if I create a python file and launch it. I use Pyhton 3.7

Traceback (most recent call last):
  File "reset.py", line 3, in <module>
    import octoprint.plugin
ModuleNotFoundError: No module named 'octoprint'

**Comment by maocypher** [comment]
I don't know where reset.py is from. It is not part from this plugin

**Comment by maocypher** [comment]
@Pavulon87 could you please merge into dev branch? Then I can prepare a new release for the fix.

I started working git flow like, with the last feature I started

**Comment by Pavulon87** [comment]
> @Pavulon87 could you please merge into dev branch? Then I can prepare a new release for the fix.
> 
> I started working git flow like, with the last feature I started

Like that #22 ?
I need to learn git a little more ;)

**Comment by maocypher** [comment]
Declined, because it is a duplicate

**Pull request closed without merging**
